defaults:
  - optimizer: discrete_evolution
  - test_function: ehrlich

random_seed: 0
log_interval: 1
num_opt_steps: 512
wandb_host: null
wandb_mode: online
project_name: holo
exp_name: dry_run
job_name: ???
__version__: ???
dtype: float32
